### ISSUE TITLE
test-release.apk not updating in Oculus Go

### ISSUE THREAD

**Issue by zweihander11** [mcclure/lovr-oculus-mobile#15]
Any reason why this may be happening?
I succeeded installing the file on the Oculus Go system but it gets stuck with an 'Updating' message once I run it.

**Comment by mcclure** [comment]
I don't actually know what an "updating" message means. That's not something lovr-oculus-mobile did.

Could you try running `adb uninstall com.whatever.the.appid.is` and then re-installing test-release.apk?

**Comment by bjornbytes** [comment]
I think this can be closed (see https://github.com/bjornbytes/lovr/issues/213)

**Comment by mcclure** [comment]
thx
