### ISSUE TITLE
lodr live-reload crashes on Oculus Quest

### ISSUE THREAD

**Issue by Ulydev** [mcclure/lovr-oculus-mobile#7]
When using the release apk along with `watch adb push --sync`, the app will eventually crash (or so does the Oculus interface say).

I am able to reproduce the bug by running a simple project:
```lua
function lovr.draw()
    lovr.graphics.print("Hello", 0, 1.7, -0.5)
end
```
and then changing anything in the code. After 1 to 3 tries the app crashes.

Only Oculus Quest has been tested, don't know if it crashes on other Android devices too.

I would love to help, but can't manage to find anything related to restarting except here: https://github.com/bjornbytes/lovr/blob/68c1b6a2013071df126bd61cca96e154409cd43c/src/modules/headset/oculus_mobile.c#L464 - or maybe it isn't linked to `lovr.event.quit('restart')`?

**Comment by Ulydev** [comment]
@bjornbytes

**Comment by bjornbytes** [comment]
That was exactly the right place!  The render callback and render data (a pointer to the Lua state) weren't getting reset on a restart, so on the next lovr.draw it was rendering with an old Lua context.

Fixed in https://github.com/bjornbytes/lovr/commit/5551f76557bb614ae3c5ad5a8150677acff75af0

**Comment by Ulydev** [comment]
You rock!

**Comment by mcclure** [comment]
Here is a precompiled binary with this fix. https://github.com/mcclure/lovr-oculus-mobile/releases/tag/lovrapp-0.3b2
